# Generated by Django 4.0.3 on 2022-03-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FetechApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='age',
            new_name='amount',
        ),
    ]
